services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_HOST: ${NEXT_PUBLIC_HOST}
        NEXT_PUBLIC_RPC_URL: ${NEXT_PUBLIC_RPC_URL}
        NEXT_PUBLIC_CONTRACT_ADDRESS: ${NEXT_PUBLIC_CONTRACT_ADDRESS}
        NEXT_PUBLIC_EXPLOER_URL: ${NEXT_PUBLIC_EXPLOER_URL}
        NEXT_PUBLIC_PRIVY_APP_ID: ${NEXT_PUBLIC_PRIVY_APP_ID}
        NEXT_PUBLIC_COINBASE_APP_ID: ${NEXT_PUBLIC_COINBASE_APP_ID}
    env_file:
      - .env
    restart: always
    expose:
      - 3000
    networks:
      - internal
      - public

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/4collection.xyz/fullchain1.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/archive/4collection.xyz/privkey1.pem:/etc/nginx/certs/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - public

networks:
  public: { }
  internal: { }